### ISSUE TITLE
Feature Request: PHP Composer Support

### ISSUE THREAD

**Issue by giovannipds** [E-goi/e-goi-wrappers#23]
Hello!

I went against the tide and tried to use this repository with [Composer](https://getcomposer.org/), the PHP package manager. After some struggle, I gave up.

It doesn't seem too difficult to support composer on this package, probably just some minor changes, as we can see someone else already tried that in some forks: https://github.com/hat-framework/e-goi and https://github.com/alexndreazevedo/egoi-api-php (cc @tigredonorte and @alexndreazevedo).

Could you please implement that? If not, just answer here and I'll see the availability for trying to make that myself (if you guys would accept a PR).

Composer is the main and official package manager for PHP and it would be awesome have compatibility with it.

Thank you in advance.

Regards, Gio.

**Comment by giovannipds** [comment]
Are you sure? You've added it as git submodules, I don't think that's the way we should do it... and it's not well configured:

    git submodule init
    fatal: No url found for submodule path 'e-goi-wrapper-php-composer' in .gitmodules

I think the right way is to split the php wrapper into a new repository then register it at [packagist](https://packagist.org).

**Comment by JoseRodrigues443** [comment]
I did not register to a public packagist, there is only found the composer code, if e-goi wants it can create a offical packagist using this submodule.

**Comment by tiaguinho** [comment]
Hi @giovannipds, we are working on a new release of the API.
For this new release, we'll publish our SDK on Composer.

**Comment by giovannipds** [comment]
@tiaguinho nice to hear that. The PHP community will be glad.

**Comment by alexndreazevedo** [comment]
@tiaguinho, thank you. I no longer maintain it. Would be great to have official support.

**Comment by renato-gomes** [comment]
This is our new PHP SDK for e-goi API V3 https://github.com/E-goi/sdk-php

**Comment by giovannipds** [comment]
@renato-gomes I'm currently not needing it but I'm very happy you've made it available to the PHP community. Next developers integrating with e-goi we'll be thank to you. =]
