### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by syshex** [E-goi/e-goi-wrappers#27]
I see no updates since a few years ago.

1- Is this being maintained? Don't want to jump on this and figure out later that it is outdated.
2- Any Maven repo for these libs ?

**Comment by syshex** [comment]
Ping ? Anybody home ?

**Comment by integrationsegoi** [comment]
Hello there,
Sorry for the late reply.
We are currently developing the wrappers for the upcoming E-goi V3 API, and old ones will be discontinued with the v3 release. 
If you need any help please feel free to contact us.

**Comment by mrmatos6837** [comment]
Is it safe to assume it's being developed in python3?

**Comment by renato-gomes** [comment]
> Is it safe to assume it's being developed in python3?

https://github.com/E-goi/sdk-python

**Comment by renato-gomes** [comment]
We have release 3 new SDk for the version 3 of our API...
https://github.com/E-goi/sdk-php
https://github.com/E-goi/sdk-java
https://github.com/E-goi/sdk-python

We have 3 more SDK's in our roadmap for this quarter.
